Add setup.sh and fix bug in video/compress.py

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,3 +1,14 @@
 #!/bin/bash
 
+check_dependency() {
+    if ! command -v $1 >/dev/null; then
+        echo "Can't find $1, please run 'setup.sh' or install it manually."
+        exit 1
+    fi
+}
+
+check_dependency adb
+check_dependency ffmpeg
+check_dependency exiftool
+
 /usr/bin/env python3 "$(dirname $0)/backup.py" "$@"
